services:
  bravka:
    build:
      context: .
      dockerfile: build/Dockerfile
      platforms:
        - linux/amd64
    ports:
      - '8090:8090'
      - '8095:8095'
    volumes:
      - ./bravka.json:/app/bravka.json
    environment:
      BRAVKA_CONFIG: ./bravka.json