name: Actions

on:
  push:
    branches: ["master"]
    tags:
      - "v*.*.*"
  pull_request:
    branches: ["master"]

env:
  GO_VERSION: 1.24.2
  GOLANGCI_LINT_VERSION: v2.1

jobs:
  checks:
    name: Test and Lint
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Test
        run: go test -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}

  docker-amd64:
    # Build and push docker image only for new tags
    if: startsWith(github.ref, 'refs/tags/v')

    name: Docker Build and Push
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: starwalkn/tokka
          tags: type=semver,pattern={{version}}
          flavor: latest=true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build amd64 and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/Dockerfile
          platforms: linux/amd64
          github-token: ${{ github.token }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}:amd64
          labels: ${{ steps.meta.outputs.labels }}
          
  docker-arm64:
    # Build and push docker image only for new tags
    if: startsWith(github.ref, 'refs/tags/v')

    name: Docker Build and Push
    runs-on: ubuntu-22.04-arm

    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: starwalkn/tokka
          tags: type=semver,pattern={{version}}
          flavor: latest=true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build amd64 and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/Dockerfile
          platforms: linux/arm64
          github-token: ${{ github.token }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}:arm64
          labels: ${{ steps.meta.outputs.labels }}
          
  docker-manifest:
    needs: [docker-amd64, docker-arm64]
    runs-on: ubuntu-22.04
  
    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Create manifest
        run: |
          docker manifest create starwalkn/tokka:latest \
            starwalkn/tokka:amd64 \
            starwalkn/tokka:arm64
  
          docker manifest push starwalkn/tokka:latest
