name: CI

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ "master" ]

env:
  GO_VERSION: 1.24.2
  GOLANGCI_LINT_VERSION: v2.1

jobs:
  test:
    if: startsWith(github.ref, 'refs/tags/v') != true

    name: Test and Coverage
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install gocovmerge (for merging coverage)
        run: |
          go install github.com/wadey/gocovmerge@latest
          echo "$GOPATH/bin" >> $GITHUB_PATH

      - name: Run tests with coverage
        run: |
          pkgs=$(go list ./... | grep -v '/cmd/' | grep -v '/dashboard/' | grep -v '/internal/')
          echo "Testing packages: $pkgs"
          
          for pkg in $pkgs; do
            go test -v -coverprofile="$pkg.cover.out" "$pkg" || exit 1
          done

          gocovmerge $(ls *.cover.out) > coverage.out

          go tool cover -func=coverage.out

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.out

      - name: Generate coverage badge
        run: |
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          PERCENT=${COVERAGE%.*}
          COLOR="red"
          if [ "$PERCENT" -ge 90 ]; then COLOR="brightgreen"; fi
          if [ "$PERCENT" -ge 75 ] && [ "$PERCENT" -lt 90 ]; then COLOR="yellow"; fi
          echo "coverage: $COVERAGE%"
          echo "![coverage](https://img.shields.io/badge/coverage-${COVERAGE}%25-${COLOR}.svg)" > coverage-badge.md

      - name: Upload coverage badge
        uses: actions/upload-artifact@v3
        with:
          name: coverage-badge
          path: coverage-badge.md

  lint:
    if: startsWith(github.ref, 'refs/tags/v') != true

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}

  docker:
    # Build and push docker image only for new tags
    if: startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: starwalkn/bravka
          tags: type=semver,pattern={{version}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/Dockerfile
          platforms: linux/amd64
          github-token: ${{ github.token }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
